### ISSUE TITLE
Error when calling "flock create"

### ISSUE THREAD

**Issue by ako977** [launchfort/flock#26]
The below is a sample of the CLI commands as I tried to create a new migration.
I am using the latest versions of flock (v3.2.4) and flock-pg (1.0.0)

```
$ ./node_modules/.bin/flock create
? Choose the type of migration Alter Table
? What table is being migrated? itinerary
? What is the file name of the migration? 2020-05-15--001--alter-table--itinerary.js
{ [Error: EISDIR: illegal operation on a directory, mkdir '/'] errno: -21, code: 'EISDIR', syscall: 'mkdir', path: '/' }
$
```

I also tried calling the command with `sudo` and still got the same error message

**Comment by dschnare** [comment]
@ako977 Double check that your .flockrc.js file is pointing to your migrations directory. In fact what's your .flockrc.js look like?

**Comment by dschnare** [comment]
@ako977 it looks like it's trying to create the `/` (root) folder for whatever reason.

**Comment by ako977** [comment]
@dschnare I think I see what happened.
I updated the version of flock and flock-pg and then did the "upgrade" instead of "init" command as the instructions say.

However, that modified my flockrc.js and wiped the reference to the migrations dir.

I think if anything maybe the docs should state that:
"... if you are upgrading from a certain version of flock (not all updates) to x version, run "upgrade" and check your flockrc to customize it again to what you had before"
